name: TGProxy. Build docker image

on: [push]

env:
  TGPROXY_DOCKER_TAG: "tgproxy:latest"
  TGPROXY_CHANNEL: "telegram://bot:token@chat_id/default?send_banner_on_startup=0"

jobs:
  docker-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ${{ env.TGPROXY_DOCKER_TAG }}
      - name: Start container
        run: |
          docker run --env "TGPROXY_CHANNEL=${{ env.TGPROXY_CHANNEL }}" -p 8888:8080 --name tgproxy --rm -d ${{ env.TGPROXY_DOCKER_TAG }} \
      - name: Ping container
        run: |
          sleep 5
          curl -v "http://localhost:8888/ping.html"
      - name: Stop container
        if: true
        run: |
          docker stop tgproxy
